detectors:
  TooManyStatements:
    max_statements: 20
    exclude:
      - "CodeSandboxMcp::StreamingExecutor#execute_streaming"
      - "CodeSandboxMcp::Server#handle_execute_code"

  TooManyMethods:
    max_methods: 25

  UncommunicativeVariableName:
    accept:
      - e

  UncommunicativeParameterName:
    accept:
      - e

  UtilityFunction:
    enabled: false

  FeatureEnvy:
    exclude:
      - "CodeSandboxMcp::Server#content_block"

  DuplicateMethodCall:
    exclude:
      - "spec/**/*"
      - "CodeSandboxMcp::Server#execute_code_with_streaming"

  LongParameterList:
    max_params: 4

  InstanceVariableAssumption:
    exclude:
      - "CodeSandboxMcp::StreamingExecutor"
      - "CodeSandboxMcp::Server"

exclude_paths:
  - vendor
  - spec
  - test