services:
  code-sandbox:
    build:
      context: .
      target: production
    image: ghcr.io/timlikesai/code-sandbox-mcp:latest
    stdin_open: true
    tty: true
    read_only: true
    network_mode: none
    tmpfs:
      - /tmp
      - /app/tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  code-sandbox-test:
    build:
      context: .
      target: test
    image: ghcr.io/timlikesai/code-sandbox-mcp:test-latest
    volumes:
      - .:/app
      - /app/vendor  # Keep gems in container
    working_dir: /app
    environment:
      - COVERAGE=true
      - COVERAGE_DIR=/tmp/coverage  # Write coverage to /tmp which is writable
    stdin_open: true
    tty: true